# Generated by Django 5.2 on 2025-05-13 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Clase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=155)),
                ("tema", models.CharField(max_length=255)),
                ("date", models.DateTimeField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("duration", models.DurationField()),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("surname", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                ("birth_date", models.DateField()),
                ("description", models.TextField()),
                ("horary", models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name="ContraOferta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("userId", models.IntegerField()),
                ("new_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("date_available", models.DateTimeField()),
                (
                    "clase",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.clase"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Propuesta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=155)),
                ("tema", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("initial_price", models.DecimalField(
                    decimal_places=2, max_digits=10)),
                ("state", models.CharField(max_length=50)),
                ("date_available", models.DateTimeField()),
                (
                    "userId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.user"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="clase",
            name="guestId",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="guest",
                to="api.user",
            ),
        ),
        migrations.AddField(
            model_name="clase",
            name="ownerId",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="owner",
                to="api.user",
            ),
        ),
        migrations.CreateModel(
            name="Pago",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("pagadorId", models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to="api.user")),
                ("beneficiarioId", models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to="api.user")),
                (
                    "clase",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.clase"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Calificacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("calificadoId", models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, related_name="calificado", to="api.user")),
                ("calificadorId", models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, related_name="calificador", to="api.user")),
                ("clase", models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to="api.clase"
                ),
                ),
                ("calificacion", models.IntegerField()),
                ("date", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Reseña",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reseña", models.TextField(max_length=255)),
                ("date", models.DateTimeField(auto_now_add=True)),
                ("reseñadoId", models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, related_name="reseñado", to="api.user")),
                ("reseñadorId", models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, related_name="reseñador", to="api.user")),
            ],
        ),
        migrations.CreateModel(
            name="Queja",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("queja", models.TextField(max_length=255)),
                ("date", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
