# Generated by Django 5.2 on 2025-05-21 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contraoferta",
            name="duration",
            field=models.DurationField(null=True),
        ),
        migrations.AddField(
            model_name="propuesta",
            name="duration",
            field=models.DurationField(null=True),
        ),
    ]
