# Generated by Django 5.2 on 2025-05-11 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_user_contraoferta"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="userId",
        ),
    ]
