# Generated by Django 5.2 on 2025-06-23 19:41

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_contraoferta_duration_propuesta_duration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contraoferta",
            name="duration",
            field=models.DurationField(default=datetime.timedelta(seconds=1800)),
        ),
        migrations.AlterField(
            model_name="contraoferta",
            name="propuestaId",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contraofertas",
                to="api.propuesta",
            ),
        ),
        migrations.AlterField(
            model_name="propuesta",
            name="duration",
            field=models.DurationField(default=datetime.timedelta(seconds=1800)),
        ),
    ]
